package com.mahanko.finalproject.controller;

public final class ParameterType {
    public static final String PATH = "path";
    public static final String USERNAME_VALIDATION_MESSAGE = "username";
    public static final String USER_SURNAME_VALIDATION_MESSAGE = "user-surname";
    public static final String LOGIN_REGISTRATION_VALIDATION_MESSAGE = "login";
    public static final String PASSWORD_VALIDATION_MESSAGE = "password";
    public static final String CONFIRM_PASSWORD_VALIDATION_MESSAGE = "confirm-password";
    public static final String MEAL_NAME_VALIDATION_MESSAGE = "meal-name";
    public static final String MEAL_COST_VALIDATION_MESSAGE = "meal-cost";
    public static final String MEAL_PICTURE_VALIDATION_MESSAGE = "meal-picture";
    public static final String INGREDIENT_NAME_VALIDATION_MESSAGE = "ingredient-name";
    public static final String INGREDIENT_CALORIES_VALIDATION_MESSAGE = "ingredient-calories";
    public static final String INGREDIENT_PROTEINS_VALIDATION_MESSAGE = "ingredient-proteins";
    public static final String INGREDIENT_FATS_VALIDATION_MESSAGE = "ingredient-fats";
    public static final String INGREDIENT_CARBOHYDRATES_VALIDATION_MESSAGE = "ingredient-carbohydrates";
    public static final String INGREDIENT_PICTURE_VALIDATION_MESSAGE = "ingredient-picture";
    public static final String SECTION_NAME_VALIDATION_MESSAGE = "section-name";
    public static final String REGISTRATION_USER_EXISTS_MESSAGE = "user-exists";
    public static final String SERVING_DATETIME_VALIDATION_MESSAGE = "incorrect-datetime";
    public static final String VALIDATION_MESSAGES = "validation_msg";
    public static final String LOGIN_VALIDATION_MESSAGE = "login_msg";
    public static final String SECTION_ADD_SUCCESSFULLY_MESSAGE = "section-add-success";
    public static final String SECTION_ADD_FAIL_MESSAGE = "section-add-fail";
    public static final String INGREDIENT_ADD_MESSAGE = "ingredient_add_msg";
    public static final String MEAL_ADDED_SUCCESSFULLY_MESSAGE = "success";
    public static final String USER_ID = "user-id";
    public static final String USER_NAME = "name";
    public static final String USER_SURNAME = "surname";
    public static final String USER_LOGIN = "login";
    public static final String USER_PASSWORD = "password";
    public static final String USER_CONFIRM_PASSWORD = "confirm-password";
    public static final String COMMAND = "command";
    public static final String INGREDIENT_ID = "ingredient-id";
    public static final String INGREDIENT_NAME = "ingredient-name";
    public static final String INGREDIENT_FATS = "ingredient-fats";
    public static final String INGREDIENT_PROTEINS = "ingredient-proteins";
    public static final String INGREDIENT_CARBOHYDRATES = "ingredient-carbohydrates";
    public static final String INGREDIENT_CALORIES = "ingredient-calories";
    public static final String INGREDIENT_WEIGHT = "ingredient-weight";
    public static final String INGREDIENT_PICTURE = "ingredient-picture";
    public static final String INGREDIENT_PICTURE_NAME = "ingredient-picture-name";
    public static final String INGREDIENT_PICTURE_SIZE = "ingredient-picture-size";
    public static final String INGREDIENTS = "ingredients";
    public static final String MENU_ITEMS = "menuItems";
    public static final String MENU_ITEM_ID = "menu-item-id";
    public static final String MENU_ITEM_COUNT = "menu-item-count";
    public static final String MENU_ITEM_NAME = "menu-item-name";
    public static final String MENU_ITEM_COST = "menu-item-cost";
    public static final String MENU_ITEM_CALORIES = "menu-item-calories";
    public static final String MENU_ITEM_PROTEINS = "menu-item-proteins";
    public static final String MENU_ITEM_FATS = "menu-item-fats";
    public static final String MENU_ITEM_CARBOHYDRATES = "menu-item-carbohydrates";
    public static final String MENU_ITEM_PICTURE = "menu-item-picture";
    public static final String MENU_ITEM_INGREDIENT = "menu-item-ingredient";
    public static final String MENU_ITEM_PICTURE_NAME = "menu-item-picture-name";
    public static final String MENU_ITEM_PICTURE_SIZE = "menu-item-picture-size";
    public static final String MENU_ITEM_SECTION_ID = "menu-item-section-id";
    public static final String SECTIONS = "sections";
    public static final String PAYMENT_TYPES = "paymentTypes";
    public static final String MENU_SECTION_ID = "menu-section-id";
    public static final String MENU_SECTION_NAME = "menu-section-name";
    public static final String ORDERS = "orders";
    public static final String USER_ORDERS = "userOrders";
    public static final String ORDER_TIME = "order-time";
    public static final String ORDER_ITEMS = "order-ITEMS";
    public static final String ORDER_PAYMENT_TYPE = "payment-type";

    private ParameterType() {
    }
}
